# Kubernetes Deployment for DevOps EKS Pipeline Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: default
  labels:
    app: devops-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
        version: v1
    spec:
      containers:
      - name: devops-app
        image: devops-eks-pipeline:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_VERSION
          value: "1.0.0"
        - name: PORT
          value: "3000"
        # Resource limits for better resource management
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        # Liveness probe to restart unhealthy containers
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness probe to control traffic routing
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      # Security context for enhanced security
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001