# Kubernetes Service for DevOps EKS Pipeline Application
apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: default
  labels:
    app: devops-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: devops-app
---
# ClusterIP Service for internal communication
apiVersion: v1
kind: Service
metadata:
  name: devops-app-internal
  namespace: default
  labels:
    app: devops-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: devops-app